# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
